// Silver Sky Events — Complete Data Store

export const CASE_STUDIES = [
  {
    id: 'windsor-royal-celestial-wedding',
    title: 'The Celestial Glass Pavilion Wedding',
    category: 'Weddings',
    tagline: 'A 600-guest transparent glass dome with 120 custom crystal chandeliers beneath the Kenyan night sky.',
    venue: 'Windsor Golf Hotel & Country Club',
    location: 'Ridgeways, Nairobi',
    guests: 600,
    date: 'December 2025',
    heroImage: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1400&q=85',
    gallery: [
      'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=1200&q=85',
    ],
    client: {
      name: 'Dr. David & Sharon Mutua',
      role: 'Bride & Groom',
    },
    narrative: {
      challenge: 'The couple desired an outdoor starlit experience during the December Nairobi rainy season without risking unpredictable tropical downpours or compromising on 360-degree views of the 18th hole greens.',
      concept: 'Silver Sky engineered a fully climate-controlled 30m x 45m clear-span German glass marquee adorned with suspended cascading white wisteria, candlelit mirrored tables, and custom royal blue velvet lounge accents.',
      infrastructure: [
        '30m x 45m Clear B-Line German Structure with transparent PVC roof',
        '120 Crystal pendant chandeliers on automated DMX dimmers',
        'Two 150 kVA synchronized silent diesel generators with auto-changeover',
        'Elevated marine-grade wooden sub-flooring with plush champagne carpet',
        'Intelligent warm-white Martin MAC Quantum profile fixtures',
      ],
      outcome: 'A completely weatherproof fairytale celebration that concluded at 4:00 AM with zero power hitches or rain interference, capturing 1.2M impressions across social media.',
      testimonial: 'Silver Sky took our seemingly impossible dream of dining beneath the stars in Nairobi December rain and engineered a breathtaking reality. The sheer precision was unmatched.',
    },
    metrics: [
      { label: 'Guests Catered', value: '600 VIPs' },
      { label: 'Rigging Time', value: '38 Hours' },
      { label: 'Uptime Reliability', value: '100.0%' },
    ],
  },
  {
    id: 'safaricom-annual-leadership-gala',
    title: 'East Africa Digital Innovation Gala',
    category: 'Corporate',
    tagline: 'High-octane corporate summit and awards night featuring a 42-meter curved P3.9 LED backdrop.',
    venue: 'Radisson Blu Hotel, Upper Hill',
    location: 'Upper Hill, Nairobi',
    guests: 450,
    date: 'November 2025',
    heroImage: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1400&q=85',
    gallery: [
      'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=85',
    ],
    client: {
      name: 'Leading Telecom & Fintech Conglomerate',
      role: 'Enterprise Corporate Client',
    },
    narrative: {
      challenge: 'Delivering broadcast-grade live stream production for 450 C-Suite leaders in Nairobi with zero latency, alongside 18 concurrent satellite breakout hubs across East Africa.',
      concept: 'A futuristic sapphire and illuminated cobalt aesthetic blending high-tech aerospace LED structures with warm candlelight dining tablescapes.',
      infrastructure: [
        '42m x 4.5m Seamless curved P3.9 indoor high-refresh LED wall',
        'L-Acoustics Kiva II Line Array audio system with Shure Axient Digital mics',
        'Robotic PTZ 4K broadcast cameras with fiber-optic transmission',
        'Custom brushed-gold metallic keynote lecterns with teleprompters',
      ],
      outcome: 'Flawless 6-hour international broadcast with seamless VIP protocol, receiving formal commendations from regional directors.',
      testimonial: 'The acoustic clarity and visual grandiosity created by Silver Sky set a new benchmark for corporate galas in Kenya. True world-class execution.',
    },
    metrics: [
      { label: 'Live Stream Viewers', value: '28,000+' },
      { label: 'C-Suite Executives', value: '450 Leaders' },
      { label: 'Production Latency', value: '<12ms' },
    ],
  },
  {
    id: 'naivasha-lakeview-twilight-soiree',
    title: 'The Great Rift Valley Sunset Soirée',
    category: 'Private',
    tagline: 'An intimate 50th birthday celebration on the shores of Lake Naivasha with glowing geometric dome pavilions.',
    venue: 'Enashipai Resort & Spa Grounds',
    location: 'Lake Naivasha, Nakuru County',
    guests: 180,
    date: 'January 2026',
    heroImage: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=1400&q=85',
    gallery: [
      'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=85',
    ],
    client: {
      name: 'Family of Ambassador J. K. Kariuki',
      role: 'Private Host',
    },
    narrative: {
      challenge: 'Transforming a raw lakeside lawn with heavy evening wind gusts into a warm, candlelit, acoustic sanctuary.',
      concept: 'Reinforced wind-rated geodetic domes styled with suspended indigenous Kenyan florals, live fire-pit ambient lounges, and acoustic shell audio.',
      infrastructure: [
        'Geodesic wind-rated dome pavilions with weighted ballasts',
        'Bespoke royal blue Chesterfield velvet lounge suites',
        'Custom hurricane lamp perimeter lighting with 400 floating beeswax candles',
        'Bose ShowMatch compact line array system for live jazz ensemble',
      ],
      outcome: 'A breathtaking sunset-to-dawn private celebration praised as the most memorable private function of the year.',
      testimonial: 'From the warm candlelight against the Lake Naivasha night to the velvet lounges, our guests felt like royalty all night long.',
    },
    metrics: [
      { label: 'Wind Resistance', value: 'Up to 75 km/h' },
      { label: 'Private Guests', value: '180 VIPs' },
      { label: 'Event Duration', value: '12 Hours' },
    ],
  },
  {
    id: 'diani-beachfront-bohemian-luxe-wedding',
    title: 'The Swahili Coast Coral Moon Wedding',
    category: 'Weddings',
    tagline: 'An oceanfront destination wedding on Diani Beach featuring bamboo archways, fairy light canopies, and barefoot luxury.',
    venue: 'Nomad Sands Grounds',
    location: 'Diani Beach, Kwale / South Coast',
    guests: 220,
    date: 'February 2026',
    heroImage: 'https://images.unsplash.com/photo-1544077960-604201fe74bc?auto=format&fit=crop&w=1400&q=85',
    gallery: [
      'https://images.unsplash.com/photo-1544077960-604201fe74bc?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=85',
    ],
    client: {
      name: 'Amina & Tariq Al-Husseini',
      role: 'Destination Bride & Groom',
    },
    narrative: {
      challenge: 'Managing high coastal humidity, sea spray, and sandy ground conditions while maintaining pristine white silk drapery and precision electrical safety.',
      concept: 'Moisture-resistant marine-grade electrical conduits, elevated teak walkways, billowing royal cobalt & ivory silk drapes, and 2,000 warm fairy light drops.',
      infrastructure: [
        'Modular elevated interlocking treated-timber boardwalks',
        'IP65 water-resistant architectural floodlights and warm fairy drop canopies',
        'Custom bamboo and brass hexagonal ceremony altar',
        'Mobile silent marine generator units with secondary solar backup',
      ],
      outcome: 'An ethereal coastal celebration where the couple exchanged vows with waves lapping 15 meters away in complete acoustic isolation.',
      testimonial: 'Planning a Diani wedding from London was daunting until we met Silver Sky. Every single detail arrived on time and surpassed our expectations.',
    },
    metrics: [
      { label: 'Fairy Light Drops', value: '2,000 Pcs' },
      { label: 'Interlocking Decking', value: '650 sqm' },
      { label: 'Logistics Fleet', value: '3 Trucks (NBO-MBA)' },
    ],
  },
  {
    id: 'diplomatic-un-state-dinner',
    title: 'Pan-African Diplomatic Summit Banquet',
    category: 'Diplomatic',
    tagline: 'A presidential-grade state dinner for 32 visiting heads of delegations and ministers.',
    venue: 'Safari Park Hotel Ballroom / Gigiri District',
    location: 'Gigiri / Thika Road, Nairobi',
    guests: 350,
    date: 'October 2025',
    heroImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1400&q=85',
    gallery: [
      'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=1200&q=85',
    ],
    client: {
      name: 'Ministry of Foreign Affairs & Regional Secretariat',
      role: 'State Protocol Delegation',
    },
    narrative: {
      challenge: 'Adhering to strict international diplomatic protocols, security clearances, presidential motorcade staging, and multi-lingual simultaneous translation.',
      concept: 'An understated, deeply regal ballroom setup with custom royal blue silk chair covers, gold candelabra centerpieces, and secure acoustic translation booths.',
      infrastructure: [
        'ISO-certified multi-channel simultaneous translation booths',
        'High-security biometric staging and perimeter lighting',
        'Custom presidential dais with gold leaf embroidery and presidential seals',
        'Zero-glare high-CRI lighting for international media broadcasting',
      ],
      outcome: 'Commended by multiple ambassadors for punctual transitions, presidential protocol precision, and exquisite decor harmony.',
      testimonial: 'Silver Sky proved why they are the go-to agency for state-level and diplomatic hospitality in East Africa.',
    },
    metrics: [
      { label: 'Delegations Represented', value: '32 Nations' },
      { label: 'Security Clearance', value: 'Level 1 Vetted' },
      { label: 'Protocol Adherence', value: '100%' },
    ],
  },
  {
    id: 'heavy-dome-infrastructure-showcase',
    title: 'The Mega-Tent & Geodesic Rigging Showcase',
    category: 'Infrastructure',
    tagline: 'Heavy event engineering: 2,500-capacity German B-Line clear marquee, trussing, and stadium power distribution.',
    venue: 'Karen Country Club Grounds',
    location: 'Karen, Nairobi',
    guests: 2500,
    date: 'January 2026',
    heroImage: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1400&q=85',
    gallery: [
      'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=1200&q=85',
    ],
    client: {
      name: 'East African Energy & Mining Forum',
      role: 'Conference Consortium',
    },
    narrative: {
      challenge: 'Erecting 1,800 square meters of pillarless, weather-tight exhibition space on uneven fairway turf within 48 hours.',
      concept: 'Heavy-duty German aluminum extrusions anchored with laser-leveled subflooring, heavy industrial HVAC ducting, and 400A 3-phase power distribution.',
      infrastructure: [
        '40m x 45m Clear-Span German B-Line structure (Zero central pillars)',
        '1,800 sqm laser-leveled elevated cassette flooring with load capacity 500kg/sqm',
        'Three 250 kVA Cummins silent diesel generator banks with automatic sync',
        'Industrial HVAC package delivering constant 21°C interior climate',
      ],
      outcome: 'Delivered 8 hours ahead of schedule; sustained 3 days of torrential downpours with zero water ingress or ground subsidence.',
      testimonial: 'The engineering capability of Silver Sky is leagues ahead of anyone else in the region. Their heavy infrastructure is European standard.',
    },
    metrics: [
      { label: 'Clear-Span Area', value: '1,800 m²' },
      { label: 'Pillarless Span', value: '40 Meters' },
      { label: 'Floor Load Capacity', value: '500 kg/m²' },
    ],
  },
];

export const PACKAGES_DATA = [
  {
    id: 'wedding-sapphire-intimate',
    name: 'Sapphire Intimate',
    badge: 'Curated Elegance',
    startingPriceKES: 480000,
    formattedPrice: 'KES 480,000',
    category: 'Weddings',
    targetAudience: 'Intimate gatherings, boutique receptions, and traditional ceremonies',
    guestCapacity: 'Up to 150 Guests',
    description: 'Designed for couples seeking refined, timeless beauty with essential luxury decor, bespoke floral styling, and atmospheric warm lighting.',
    inclusions: [
      'Complete event coordination & on-the-day bridal concierge',
      'Bespoke bridal table styling with custom linen & velvet runner',
      'Fresh floral centerpieces with local & imported Ecuadorian roses',
      'Ambient warm-white LED uplighting (16 wireless fixtures)',
      'Luxury Chiavari or Phoenix acrylic chairs with silk seat pads',
      'Custom gold-framed welcome mirror & personalized table stationery',
      'Full setup, professional staging, and strike-down crew',
    ],
    equipmentDetails: [
      '16x Wireless battery-powered RGBWA+UV uplighters',
      'High-clarity speech PA system with 2 wireless Shure microphones',
      'Custom cake display plinth with directional spotlight',
    ],
    depositRequiredPct: 40,
    depositAmountKES: 192000,
  },
  {
    id: 'wedding-royal-opulence',
    name: 'Royal Opulence',
    badge: 'Most Popular',
    startingPriceKES: 1350000,
    formattedPrice: 'KES 1,350,000',
    category: 'Weddings',
    targetAudience: 'Grand celebrations, high-society weddings, and luxury estate affairs',
    guestCapacity: '250 – 500 Guests',
    description: 'Our signature luxury wedding production. A breathtaking fusion of suspended floral canopies, crystal chandeliers, mirror dancefloors, and intelligent ambient lighting.',
    inclusions: [
      'End-to-end event design, 3D venue renders & floor plan CAD modeling',
      'Grand bridal entrance runway with low-fog dry ice clouds & cold spark fountains',
      'Suspended floral ceiling installations & 20+ crystal droplet chandeliers',
      'Custom seamless high-gloss white or gold-mirrored dance floor',
      'VIP lounge suite styling with velvet Chesterfield couches & marble cocktail tables',
      'Backlit photo-moment floral art installation with neon couple monogram',
      'Dedicated wedding day director and 12-member hospitality coordination crew',
      'Full audio-visual production, live band line-array, and intelligent stage moving heads',
    ],
    equipmentDetails: [
      'Line-array concert audio with dedicated digital sound engineer',
      '12x Beam/Spot moving heads with custom gobo texture projection',
      '4x Sparkular cold pyrotechnics + low-lying fog generator',
      'Dedicated 80 kVA silent backup diesel generator with auto-switchover',
    ],
    depositRequiredPct: 40,
    depositAmountKES: 540000,
  },
  {
    id: 'wedding-celestial-grandeur',
    name: 'Celestial Grandeur',
    badge: 'Ultra-Bespoke',
    startingPriceKES: 2900000,
    formattedPrice: 'KES 2,900,000',
    category: 'Weddings',
    targetAudience: 'VVIP, diplomatic, and destination weddings requiring full structural transformation',
    guestCapacity: '500 – 1,200+ Guests',
    description: 'An architectural and artistic tour de force. We build a custom German glass marquee over raw terrain, complete with climate control, curved LED video, and Michelin-worthy dining decor.',
    inclusions: [
      'Pillarless German clear-span glass dome structure tailored to your grounds',
      'Laser-leveled cassette sub-flooring fully carpeted in virgin champagne fleece',
      'Climate control HVAC systems maintaining optimal 20°C interior comfort',
      'Massive curved 4K LED video screen for cinematic couple documentaries & live feed',
      'Ultra-luxury velvet dining chairs, gold cutlery, crystal glassware, and custom charger plates',
      'Overhead kinetic light fixtures and custom automated lighting shows',
      'Full VVIP protocol, presidential security liaison, and helicopter landing coordination',
      '48-hour prior setup window ensuring zero-stress rehearsals and sound checks',
    ],
    equipmentDetails: [
      'German B-Line Clear Tent Structure with reinforced storm wind anchors',
      '2x 150 kVA Synchronized redundant generator banks',
      'Robotic broadcast camera package with satellite uplink capability',
      'Custom architectural entrance tunnel with infinity LED mirrors',
    ],
    depositRequiredPct: 40,
    depositAmountKES: 1160000,
  },
  {
    id: 'corporate-executive-summit',
    name: 'Executive Summit',
    badge: 'Corporate Standard',
    startingPriceKES: 650000,
    formattedPrice: 'KES 650,000',
    category: 'Corporate',
    targetAudience: 'High-level executive conferences, investor roundtables, and board summits',
    guestCapacity: '100 – 250 Delegates',
    description: 'Crisp corporate branding, zero-latency digital acoustics, seamless presentation switching, and broadcast-ready stage backdrops.',
    inclusions: [
      'Custom branded executive stage backdrop with 3D acrylic corporate crest',
      'High-definition dual presentation screens with seamless Roland switchers',
      'Full conference audio with push-to-talk delegate microphones & wireless lavaliers',
      'Executive registration zone with digital check-in counters & branded lanyard stations',
      'Comfortable ergonomic leather conference seating with stationery packs',
      'Dedicated technical director, audio technician, and stage manager throughout',
    ],
    equipmentDetails: [
      'Dual 85" Ultra-HD commercial display monitors or P2.9 LED wall segment',
      'Yamaha digital console with acoustic feedback suppression',
      'Live presentation clickers, confidence monitor, and countdown timers',
    ],
    depositRequiredPct: 40,
    depositAmountKES: 260000,
  },
  {
    id: 'corporate-annual-gala',
    name: 'Annual Gala & Awards',
    badge: 'Enterprise Choice',
    startingPriceKES: 1600000,
    formattedPrice: 'KES 1,600,000',
    category: 'Corporate',
    targetAudience: 'End-of-year corporate galas, regional awards ceremonies, and multinational celebrations',
    guestCapacity: '300 – 800 Attendees',
    description: 'An electrifying red-carpet awards night production. Immersive dynamic lighting, giant LED walls, customized award stingers, and luxury banqueting decor.',
    inclusions: [
      '50-meter outdoor red carpet arrival experience with custom press media wall & stanchions',
      'Giant 36-meter high-refresh P3.9 LED screen with custom motion graphics & award stingers',
      'Full intelligent theatrical stage lighting with motorized wash, beam, and spotlight profiles',
      'Black-tie dinner decor with satin tablecloths, gold accents, and architectural uplighting',
      'Broadcast live stream to YouTube/LinkedIn and multi-camera live video switching',
      'Stage pyrotechnics, confetti cannons for trophy winners, and custom podiums',
    ],
    equipmentDetails: [
      'Full L-Acoustics / RCF line-array sound system calibrated for large ballrooms',
      'Chamsys / grandMA lighting console with pre-programmed award cues',
      'Dual CO2 cryo jets + 4x automated stage confetti blowers',
      '100 kVA silent generator backup with zero-second transfer switch',
    ],
    depositRequiredPct: 40,
    depositAmountKES: 640000,
  },
  {
    id: 'infrastructure-german-dome',
    name: 'German Clear-Span Marquee Hire',
    badge: 'Heavy Infrastructure',
    startingPriceKES: 550000,
    formattedPrice: 'KES 550,000 / Day',
    category: 'Infrastructure',
    targetAudience: 'Planners, corporate event managers, and outdoor luxury weddings',
    guestCapacity: '200 to 3,000+ Guests',
    description: 'European-certified German B-Line clear and white marquee structures. Zero internal pillars, maximum architectural grandeur, and total weatherproofing.',
    inclusions: [
      'Span widths available: 15m, 20m, 25m, 30m, 40m with modular bay lengths',
      'Heavy-duty hot-dipped galvanized steel connections & extruded aluminum rafters',
      'Wind-load certified up to 100 km/h with heavy earth anchoring or concrete ballasts',
      'Clear transparent PVC roof covers or blackout luxury white covers',
      'Elevated wooden or aluminum cassette sub-floor options available',
      'Comprehensive safety sign-off, fire retardant certifications, and structural engineer approval',
    ],
    equipmentDetails: [
      'Clear PVC walls with panoramic window options',
      'Heavy-duty industrial anchoring pegs (1.2m forged steel)',
      'Integral aluminum gutters for rapid rainwater drainage',
    ],
    depositRequiredPct: 40,
    depositAmountKES: 220000,
  },
];

export const INFRASTRUCTURE_CATALOG = [
  {
    name: 'Clear German B-Line Domes',
    specs: '15m to 40m clear span, modular length',
    startingAt: 'KES 1,200 / sqm',
    image: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'Curved P3.9 Indoor/Outdoor LED Screen',
    specs: 'Up to 60 meters wide, 4K NovaStar processing',
    startingAt: 'KES 15,000 / panel / day',
    image: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'Concert Line Array Audio System',
    specs: 'L-Acoustics / RCF line array + digital consoles',
    startingAt: 'KES 180,000 / day',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'Intelligent Beam & Wash Moving Heads',
    specs: 'Martin / Robe 380W moving heads + DMX',
    startingAt: 'KES 8,000 / fixture',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'Silent Diesel Generator Fleets',
    specs: '60 kVA, 100 kVA, 150 kVA, 250 kVA with auto-switch',
    startingAt: 'KES 65,000 / day',
    image: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'Royal Velvet & Gold Furniture Suites',
    specs: 'Chesterfield sofas, Phoenix chairs, marble tables',
    startingAt: 'KES 450 / chair | KES 15,000 / lounge set',
    image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=600&q=80',
  },
];

export const REGIONS_DATA = [
  {
    id: 'nairobi-metropolitan',
    slug: 'nairobi',
    name: 'Nairobi & Environs',
    badge: 'Headquarters & Primary Hub',
    headline: 'Luxury Event Coordination & Clear Marquees in Nairobi',
    subheadline: 'Serving Karen, Gigiri, Muthaiga, Westlands, Runda, and Greater Nairobi with zero-lag mobilization.',
    description: 'As our primary operations hub, our 35,000 sq ft logistics depot in Nairobi houses Kenya’s most extensive fleet of German clear-span marquees, high-end Italian furniture, line-array audio, and concert lighting. From diplomatic galas in Gigiri to fairytale estate weddings in Karen and Muthaiga, our seasoned team delivers flawless events with 24/7 technical backup.',
    heroImage: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=85',
    coverageCounties: ['Nairobi County', 'Kiambu (Runda/Thika)', 'Kajiado (Ngong/Kitengela)', 'Machakos'],
    popularVenues: [
      { name: 'Windsor Golf Hotel & Country Club', neighborhood: 'Ridgeways', capacity: '1,500 Guests', style: 'Golf Course Lawn & Lakeview' },
      { name: 'Karen Country Club Grounds', neighborhood: 'Karen', capacity: '1,200 Guests', style: 'Heritage Colonial Fairways' },
      { name: 'Hemingways Nairobi', neighborhood: 'Karen', capacity: '350 Guests', style: 'Plantation Luxury & Boutique Lawn' },
      { name: 'Safari Park Hotel & Casino', neighborhood: 'Thika Road', capacity: '2,000 Guests', style: 'Tropical Flora & Grand Ballrooms' },
      { name: 'Radisson Blu Hotel Upper Hill', neighborhood: 'Upper Hill', capacity: '600 Guests', style: 'Contemporary Five-Star Ballroom' },
    ],
    regionalHighlights: [
      { title: 'Zero Transport Surcharges', description: 'Immediate mobilization within Nairobi metropolitan limits with zero interstate transit fees.' },
      { title: 'County Permit Management', description: 'We manage full NEMA noise permits, NCC event licenses, and Red Cross medical liaisons directly.' },
      { title: 'Synchronized Twin Generators', description: 'Dual backup generator redundancies ensure uninterrupted luxury audio and lighting throughout your event.' },
    ],
    localFleet: {
      depot: 'Silver Sky Logistics Center, Enterprise Rd / Karen Hub, Nairobi',
      transportTimeline: 'Same-day mobilization (2–4 hours)',
      teamCapacity: '120 Full-time event directors, riggers, and stylists',
    },
    startingPriceNote: 'Wedding packages from KES 480,000 | Corporate from KES 650,000',
  },
  {
    id: 'mombasa-diani-coast',
    slug: 'mombasa-diani',
    name: 'Mombasa & Diani Coast',
    badge: 'Coastal & Destination Weddings',
    headline: 'Beachfront Destination Weddings & Ocean Galas in Diani & Mombasa',
    subheadline: 'Swahili coast glamour, sea-spray resistant rigging, tropical floral architecture, and barefoot luxury.',
    description: 'Transforming the white sands of Diani, Nyali, Kilifi, and Watamu into starlit oceanside celebrations. We overcome coastal humidity and sea winds with specialized marine-grade electronics, elevated teak flooring, moisture-sealed lighting fixtures, and custom tropical bamboo pavilions.',
    heroImage: 'https://images.unsplash.com/photo-1544077960-604201fe74bc?auto=format&fit=crop&w=1200&q=85',
    coverageCounties: ['Mombasa County', 'Kwale (Diani / Ukunda)', 'Kilifi (Vipingo / Watamu)', 'Malindi / Lamu'],
    popularVenues: [
      { name: 'Vipingo Ridge Beach Club', neighborhood: 'Kilifi Coast', capacity: '800 Guests', style: 'Clifftop & Private Beachfront' },
      { name: 'The Sands at Nomad', neighborhood: 'Diani Beach', capacity: '400 Guests', style: 'Indigenous Forest & Coral Beach' },
      { name: 'Serena Beach Resort & Spa', neighborhood: 'Shanzu / Mombasa', capacity: '650 Guests', style: 'Swahili Village Architecture' },
      { name: 'Medina Palms', neighborhood: 'Watamu', capacity: '300 Guests', style: 'Moroccan-Arabic Luxe Villas' },
    ],
    regionalHighlights: [
      { title: 'Marine-Grade Electrical Systems', description: 'IP65-rated waterproof cabling, distribution boards, and sealed LED wash fixtures designed for high-salinity air.' },
      { title: 'Elevated Sand Decking', description: 'Interlocking marine-treated timber boardwalks and platforms that protect high heels while maintaining sea views.' },
      { title: 'Nairobi-to-Coast Dedicated Logistics', description: 'Scheduled long-haul transport trucks with cushioned air-ride suspension to protect fragile chandeliers.' },
    ],
    localFleet: {
      depot: 'Mombasa Regional Logistics Depot, Shimanzi & Diani Staging Base',
      transportTimeline: '24-hour advance site staging prior to event day',
      teamCapacity: '45 Coastal rigging technicians and beach styling crew',
    },
    startingPriceNote: 'Coastal destination packages from KES 850,000',
  },
  {
    id: 'naivasha-nakuru-rift',
    slug: 'naivasha-nakuru',
    name: 'Naivasha & Nakuru',
    badge: 'Rift Valley Escapes',
    headline: 'Highland Sunset Celebrations & Vineyard Receptions in Naivasha',
    subheadline: 'Lakeview marquees, heated evening pavilions, and breathtaking Great Rift Valley backdrops.',
    description: 'Lake Naivasha and Nakuru are Kenya’s premier weekend wedding destinations. Our Rift Valley engineering specialists design wind-anchored clear marquees that handle sudden afternoon gusts and transform into warm, candlelit, heated sanctuaries once the cool African night sets in.',
    heroImage: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=1200&q=85',
    coverageCounties: ['Nakuru County', 'Naivasha Basin', 'Gilgil / Elementaita', 'Nyandarua / Kinangop'],
    popularVenues: [
      { name: 'Enashipai Resort & Spa Grounds', neighborhood: 'Moi South Lake Rd, Naivasha', capacity: '1,200 Guests', style: 'Manicured Lakeside Lawns' },
      { name: 'Great Rift Valley Lodge & Golf', neighborhood: 'Green Park, Naivasha', capacity: '600 Guests', style: 'Panoramic Valley Escarpment' },
      { name: 'Lake Naivasha Sopa Resort', neighborhood: 'South Lake Rd', capacity: '900 Guests', style: 'Acacia Forests with Resident Wildlife' },
      { name: 'Lake Elementaita Serena Camp', neighborhood: 'Lake Elementaita', capacity: '350 Guests', style: 'Flamingo Shorelines & Luxury Canvas' },
    ],
    regionalHighlights: [
      { title: 'Wind-Engineered Ground Ballasts', description: 'Engineered for up to 80 km/h wind shear off the lake with 1.2m steel soil spikes and concrete dead-weights.' },
      { title: 'Outdoor Patio Heating Solutions', description: 'Commercial stainless-steel pyramid flame heaters and heated radiant canopies for cold mountain evenings.' },
      { title: 'Wildlife Protocol Compliance', description: 'Silent sound zoning and low-glare warm light arrays that respect sanctuary wildlife guidelines.' },
    ],
    localFleet: {
      depot: 'Naivasha Moi South Lake staging hub + Nairobi convoy',
      transportTimeline: '1.5-hour direct highway transit from Nairobi',
      teamCapacity: '35 Highland event coordinators and heavy riggers',
    },
    startingPriceNote: 'Naivasha packages starting from KES 620,000',
  },
  {
    id: 'kisumu-western-lake',
    slug: 'kisumu-western',
    name: 'Kisumu & Western Lake',
    badge: 'Grand Lakeside Galas',
    headline: 'State-Level Conferences & Grand Celebrations in Kisumu & Western Kenya',
    subheadline: 'Bespoke event architecture along Lake Victoria, Kakamega, Eldoret, and the Great Lakes basin.',
    description: 'We bring Nairobi-grade heavy infrastructure to Western Kenya. Specializing in high-capacity clear marquees for 1,000 to 5,000 delegates, political summits, traditional nuptials, and corporate launches across Kisumu, Eldoret, Kakamega, and Homabay.',
    heroImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=85',
    coverageCounties: ['Kisumu County', 'Uasin Gishu (Eldoret)', 'Kakamega County', 'Siaya & Homa Bay'],
    popularVenues: [
      { name: 'Acacia Premier Hotel Kisumu', neighborhood: 'Milimani, Kisumu', capacity: '500 Guests', style: 'Rooftop Lakeview & Ballrooms' },
      { name: 'Grand Royal Swiss Hotel', neighborhood: 'Riat Hills, Kisumu', capacity: '2,500 Guests', style: 'Hillside Grand Exhibition Lawns' },
      { name: 'Boma Inn Eldoret', neighborhood: 'Elgon View, Eldoret', capacity: '800 Guests', style: 'Highland Manicured Lawns' },
      { name: 'Ciala Resort', neighborhood: 'Daraja Mbili, Kisumu', capacity: '1,500 Guests', style: 'Scenic Countryside Luxury' },
    ],
    regionalHighlights: [
      { title: 'Mega-Capacity Structural Spans', description: '40m-wide clear German marquees accommodating up to 3,500 seated guests with zero visual obstruction.' },
      { title: 'High-Volume Cooling & HVAC', description: 'Ducted air-conditioning keeping humid lakeside afternoon temperatures crisp and comfortable.' },
      { title: 'Direct Eldoret & Kisumu Logistics Depot', description: 'Pre-positioned heavy rigging and staging equipment eliminating cross-country delays.' },
    ],
    localFleet: {
      depot: 'Kisumu City Staging Yard, Kibos Rd & Eldoret Hub',
      transportTimeline: 'Pre-positioned local equipment + specialized convoys',
      teamCapacity: '50 Regional engineers and hospitality specialists',
    },
    startingPriceNote: 'Western Kenya packages from KES 690,000',
  },
  {
    id: 'mt-kenya-nanyuki',
    slug: 'mt-kenya-nanyuki',
    name: 'Mount Kenya & Nanyuki',
    badge: 'Equatorial Alpine Luxury',
    headline: 'Fairmont & Safari Lodge Weddings at the Foot of Mount Kenya',
    subheadline: 'Timeless colonial charm, open fire pits, celestial mountain views, and luxury tented ballrooms.',
    description: 'From Nanyuki to Timau and Meru, create unforgettable celebrations under the shadow of Batian and Nelion. Our alpine event productions integrate open flame fireplaces, fur and velvet lounge textures, and warm candlelight that contrasts with crisp mountain breezes.',
    heroImage: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=1200&q=85',
    coverageCounties: ['Laikipia County (Nanyuki)', 'Nyeri County', 'Meru County', 'Embu County'],
    popularVenues: [
      { name: 'Fairmont Mount Kenya Safari Club', neighborhood: 'Nanyuki Equator', capacity: '600 Guests', style: 'Equatorial Heritage Estate & Lawns' },
      { name: 'Ol Pejeta Bush Camp & Safari Grounds', neighborhood: 'Sweetwaters, Laikipia', capacity: '400 Guests', style: 'Conservancy Wilderness Luxe' },
      { name: 'Maiyan Luxury Resort', neighborhood: 'Nanyuki Road', capacity: '1,000 Guests', style: 'Equestrian Estate & Infinity Lawns' },
      { name: 'The Serena Mountain Lodge Grounds', neighborhood: 'Mount Kenya Forest', capacity: '250 Guests', style: 'Indigenous Forest Tree Canopy' },
    ],
    regionalHighlights: [
      { title: 'Thermal Comfort Engineering', description: 'Double-insulated ceiling linings and enclosed glass walls that retain day warmth into 8°C mountain nights.' },
      { title: 'Rustic-Luxe Styling & Woodcraft', description: 'Handcrafted local olive wood grazing boards, wrought-iron candelabras, and live stone firepits.' },
      { title: 'Equator Ceremony Styling', description: 'Custom ceremonial altars positioned precisely across the 0°00\' latitude line.' },
    ],
    localFleet: {
      depot: 'Nanyuki Town staging yard & Central Kenya mobile unit',
      transportTimeline: '2.5 hours transit from Nairobi logistics center',
      teamCapacity: '30 Alpine event technicians and bridal concierges',
    },
    startingPriceNote: 'Mount Kenya bespoke packages from KES 650,000',
  },
];

export const GOOGLE_PROFILE = {
  businessName: 'Silver Sky Events & Infrastructure Ltd',
  rating: 4.9,
  totalReviews: 148,
  address: 'Karen Office Park & Industrial Logistics Center, Nairobi, Kenya',
  phone: '+254 700 123 456',
  hours: 'Open Mon - Sat: 8:00 AM – 7:00 PM | 24/7 Event Operations Team',
  googleMapsUrl: 'https://maps.google.com/?q=Silver+Sky+Events+Nairobi+Kenya',
};

export const GOOGLE_REVIEWS_DATA = [
  {
    id: 'rev-1',
    authorName: 'Brenda Wangari-Omondi',
    authorRole: 'Bride (Windsor Golf Hotel Reception)',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    timeAgo: '2 weeks ago',
    eventType: 'Luxury Clear Dome Wedding (550 Guests)',
    venue: 'Windsor Golf Hotel & Country Club',
    reviewText: 'Silver Sky completely blew our expectations out of the water! We booked their Royal Opulence package for 550 guests. The German clear tent with cascading wisteria and crystal chandeliers looked like something out of a royal fairy tale. What impressed my husband most was the generator sync—we didn’t have a single power flicker all night even when the heavy rain started. Worth every single shilling!',
    verified: true,
    likesCount: 24,
  },
  {
    id: 'rev-2',
    authorName: 'Patrick M. Kilonzo',
    authorRole: 'Head of Corporate Affairs, Financial Services Group',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    timeAgo: '1 month ago',
    eventType: 'Annual C-Suite Gala & Awards (400 Delegates)',
    venue: 'Radisson Blu Hotel Upper Hill',
    reviewText: 'From a corporate standpoint, Silver Sky is the most disciplined event infrastructure partner in East Africa. Their audio-visual team deployed a 36-meter curved LED screen with zero pixel glitches and delivered simultaneous translation for 12 diplomatic delegations seamlessly. Punctual, polite, and totally unflappable under pressure.',
    verified: true,
    likesCount: 19,
  },
  {
    id: 'rev-3',
    authorName: 'Amina Al-Husseini',
    authorRole: 'Bride (Diani Beach Destination Wedding)',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    timeAgo: '3 weeks ago',
    eventType: 'Coastal Destination Wedding (220 Guests)',
    venue: 'The Sands at Nomad, Diani Beach',
    reviewText: 'Planning our wedding from the UK was stressful until we hired Silver Sky. They handled everything from the trucks coming down from Nairobi to the elevated wooden platforms on the sand so my grandmother could walk safely. The warm candlelight under the Swahili stars was breathtaking. All our international guests were speechless!',
    verified: true,
    likesCount: 31,
  },
  {
    id: 'rev-4',
    authorName: 'Dr. Evans Kiprono',
    authorRole: 'Host, 50th Golden Jubilee Soirée',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    timeAgo: '2 months ago',
    eventType: 'Private Milestone Celebration (180 Guests)',
    venue: 'Enashipai Resort & Spa, Lake Naivasha',
    reviewText: 'The team managed the Lake Naivasha winds with true engineering skill. We had geodetic heated dome tents, live fire pits, and acoustic jazz sound that filled the lawn without disturbing the nearby wildlife conservancy. Our guests are still texting us weeks later saying it was the best private party they’ve attended.',
    verified: true,
    likesCount: 16,
  },
  {
    id: 'rev-5',
    authorName: 'Grace Njeri Muthemba',
    authorRole: 'Managing Director, Pan-African Trade Summit',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    timeAgo: '3 months ago',
    eventType: 'Diplomatic Trade Expo (1,200 Delegates)',
    venue: 'Gigiri Diplomatic District / Safari Park',
    reviewText: 'Silver Sky handled our 3-day expo with presidential-grade security and protocol compliance. Their mobile generator fleets and laser-leveled flooring provided an exhibition ground that matched European standards. I will never work with another decor and rigging firm in Kenya.',
    verified: true,
    likesCount: 42,
  },
];

export const FB_POSTS = [
  {
    id: 'fb-post-1',
    message: '✨ An enchanting twilight reveal at Windsor Golf Hotel & Country Club. Our 30m German clear-span dome adorned with 120 custom crystal droplet chandeliers and cascading wisteria. Pure romance under the Kenyan sky.',
    created_time: '2 days ago',
    mediaUrl: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=85',
    permalink_url: 'https://facebook.com/silverskyevents',
    likes_count: 482,
    comments_count: 59,
    eventType: 'Wedding',
    venueTag: 'Windsor Golf Hotel, Nairobi',
  },
  {
    id: 'fb-post-2',
    message: '🚀 Soundcheck & visual calibration for the Pan-African Fintech Leadership Summit at Radisson Blu Upper Hill. 42-meter curved P3.9 LED screen powered by NovaStar UHD, paired with L-Acoustics line array. Zero latency, pure immersion.',
    created_time: '5 days ago',
    mediaUrl: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1200&q=85',
    permalink_url: 'https://facebook.com/silverskyevents',
    likes_count: 319,
    comments_count: 27,
    eventType: 'Corporate',
    venueTag: 'Radisson Blu Hotel, Upper Hill',
  },
  {
    id: 'fb-post-3',
    message: '🌊 Barefoot luxury in Diani Beach! Our coastal rigging team deployed interlocking treated-timber boardwalks, weather-sealed warm candlelit lanterns, and a custom bamboo ceremony arch.',
    created_time: '1 week ago',
    mediaUrl: 'https://images.unsplash.com/photo-1544077960-604201fe74bc?auto=format&fit=crop&w=1200&q=85',
    permalink_url: 'https://facebook.com/silverskyevents',
    likes_count: 561,
    comments_count: 73,
    eventType: 'Wedding',
    venueTag: 'The Sands at Nomad, Diani Beach',
  },
  {
    id: 'fb-post-4',
    message: '⛺ Heavy engineering at work: Erecting 1,800 sqm of pillarless German B-Line clear marquee at Karen Country Club. Wind-tested, laser-leveled cassette subflooring, and twin synchronized 150 kVA generators.',
    created_time: '2 weeks ago',
    mediaUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1200&q=85',
    permalink_url: 'https://facebook.com/silverskyevents',
    likes_count: 274,
    comments_count: 34,
    eventType: 'Infrastructure',
    venueTag: 'Karen Country Club Grounds, Nairobi',
  },
];
